#!/usr/bin/env python3
"""Export DrawSeed table (draw_id 9-236) to SQL INSERT statements."""

import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from pathlib import Path
from src.modules.db_connection import DatabaseConnection

db = DatabaseConnection()
db.connect()
rows = db.query("SELECT * FROM DrawSeed WHERE draw_id BETWEEN 9 AND 236 ORDER BY draw_id, seed_number")
db.disconnect()

lines = [
    "-- Generated by scripts/recalculation/export_drawseed.py",
    "-- Table: DrawSeed",
    "-- Rows: %d" % len(rows),
    "",
]
for r in rows:
    is_actual = "TRUE" if r["is_actual_seeding"] else "FALSE"
    lines.append(
        "INSERT INTO DrawSeed (draw_id, player_id, seed_number, seeding_points, is_actual_seeding) "
        "VALUES (%s, %s, %s, %s, %s);"
        % (r["draw_id"], r["player_id"], r["seed_number"], r["seeding_points"], is_actual)
    )

lines.append("")
out = Path(ROOT) / "data" / "sql" / "generated" / "drawseed.sql"
out.write_text("\n".join(lines), encoding="utf-8")
print("Written %d rows to %s" % (len(rows), out))
