#!/usr/bin/env python3
"""
Generate missing WeeklyRanking rows for ranking_week 7 and 8 of 2026.

Run from project root:
    python3 scripts/recalculation/generate_ranking_year2026_weeks7and8.py

Outputs:
    - Inserts into WeeklyRanking table
    - data/sql/generated/weeklyranking_year2026_weeks7and8.sql
    - data/extracts/generated/weeklyranking_year2026_weeks7and8.xlsx
"""
from __future__ import annotations

import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from src.modules.db_connection import DatabaseConnection
from src.modules.calculate_weekly_ranking import calculate_weekly_ranking


WEEKS_TO_GENERATE = [
    (2026, 7),
    (2026, 8),
]

COLUMNS = [
    "player_id", "age_category_id", "gender_id",
    "ranking_year", "ranking_week", "total_points", "rank_position",
]

SQL_OUTPUT = os.path.join(ROOT, "data", "sql", "generated",
                          "weeklyranking_year2026_weeks7and8.sql")
XLSX_OUTPUT = os.path.join(ROOT, "data", "extracts", "generated",
                           "weeklyranking_year2026_weeks7and8.xlsx")


def export_sql(all_rows):
    os.makedirs(os.path.dirname(SQL_OUTPUT), exist_ok=True)
    with open(SQL_OUTPUT, "w") as f:
        f.write("-- Generated by scripts/recalculation/"
                "generate_ranking_year2026_weeks7and8.py\n")
        f.write("-- Table: WeeklyRanking\n")
        f.write(f"-- Rows: {len(all_rows)}\n\n")
        for r in all_rows:
            vals = ", ".join(str(r[c]) for c in COLUMNS)
            f.write(
                f"INSERT INTO WeeklyRanking "
                f"({', '.join(COLUMNS)}) VALUES ({vals});\n"
            )
    print(f"  ✓ SQL exported to {SQL_OUTPUT}")


def export_xlsx(all_rows):
    from openpyxl import Workbook
    from openpyxl.styles import Font, Alignment, PatternFill

    os.makedirs(os.path.dirname(XLSX_OUTPUT), exist_ok=True)
    wb = Workbook()
    ws = wb.active
    ws.title = "WeeklyRanking"

    header_font = Font(name="Arial", bold=True, size=11)
    header_fill = PatternFill("solid", fgColor="D9E1F2")
    header_align = Alignment(horizontal="center")
    data_font = Font(name="Arial", size=11)

    for col_idx, col_name in enumerate(COLUMNS, 1):
        cell = ws.cell(row=1, column=col_idx, value=col_name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_align

    for row_idx, r in enumerate(all_rows, 2):
        for col_idx, col_name in enumerate(COLUMNS, 1):
            cell = ws.cell(row=row_idx, column=col_idx, value=r[col_name])
            cell.font = data_font

    for col_idx, col_name in enumerate(COLUMNS, 1):
        ws.column_dimensions[chr(64 + col_idx)].width = max(len(col_name) + 4, 14)

    wb.save(XLSX_OUTPUT)
    print(f"  ✓ XLSX exported to {XLSX_OUTPUT}")


def main():
    db = DatabaseConnection()
    if not db.connect():
        print("✗ Failed to connect to database")
        return

    print("Loading data...")
    points_history = db.query("SELECT * FROM PointsHistory ORDER BY id")
    tournaments_list = db.query(
        "SELECT tournament_id, tournament_year, tournament_week FROM Tournaments"
    )
    players = db.query("SELECT player_id, gender_id FROM Players")

    print(f"  {len(points_history)} PointsHistory records")
    print(f"  {len(tournaments_list)} tournaments")
    print(f"  {len(players)} players")

    tournaments_dict = {
        t["tournament_id"]: {"year": t["tournament_year"], "week": t["tournament_week"]}
        for t in tournaments_list
    }
    player_gender = {p["player_id"]: p["gender_id"] for p in players}

    cur = db.connection.cursor()
    total_inserted = 0
    all_rows = []

    for year, week in WEEKS_TO_GENERATE:
        existing = db.query_params(
            "SELECT COUNT(*) AS cnt FROM WeeklyRanking "
            "WHERE ranking_year = %s AND ranking_week = %s",
            (year, week),
        )
        if existing and int(existing[0]["cnt"]) > 0:
            print(f"\n⚠ ranking_week {week}/{year} already has "
                  f"{existing[0]['cnt']} rows — skipping")
            existing_rows = db.query_params(
                "SELECT player_id, age_category_id, gender_id, "
                "ranking_year, ranking_week, total_points, rank_position "
                "FROM WeeklyRanking "
                "WHERE ranking_year = %s AND ranking_week = %s",
                (year, week),
            )
            all_rows.extend(existing_rows)
            continue

        print(f"\nCalculating ranking_week {week}/{year}...")
        rankings = calculate_weekly_ranking(
            ranking_year=year,
            ranking_week=week,
            points_history=points_history,
            tournaments=tournaments_dict,
            player_gender=player_gender,
        )

        for r in rankings:
            cur.execute(
                "INSERT INTO WeeklyRanking "
                "(player_id, age_category_id, gender_id, "
                " ranking_year, ranking_week, total_points, rank_position) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s)",
                (
                    r["player_id"],
                    r["age_category_id"],
                    r["gender_id"],
                    r["ranking_year"],
                    r["ranking_week"],
                    r["total_points"],
                    r["rank_position"],
                ),
            )

        db.connection.commit()
        print(f"  ✓ Inserted {len(rankings)} rows for week {week}/{year}")
        total_inserted += len(rankings)
        all_rows.extend(rankings)

    cur.close()
    db.disconnect()

    if all_rows:
        print(f"\nExporting {len(all_rows)} rows...")
        export_sql(all_rows)
        export_xlsx(all_rows)

    print(f"\nDone. {total_inserted} total rows inserted.")


if __name__ == "__main__":
    main()
