#!/usr/bin/env python3
"""
DrawPlayers validation
======================

This module validates DrawPlayers data generated by
scripts/generation/generate_draw_players.py.

It performs ONLY validation:
- no generation
- no database writes

Source of truth: Rules.md
"""

from __future__ import annotations

from datetime import datetime, date, time, timedelta, timezone
from typing import List, Dict, Optional, Set


# ============================================================
# VALIDATION: DRAW PUBLICATION DEADLINE
# ============================================================

def validate_draw_publication_deadline(
    tournament_start_date: date,
    draw_generated_at: datetime,
) -> None:
    """
    Validate draw publication deadline.

    Rule (Rules.md):
    - Draw must be published no later than the day before tournament start,
      at 18:00 local time.

    Raises:
        ValueError if the deadline is violated.
    """
    # Tournament start minus one day at 18:00
    deadline = datetime.combine(
        tournament_start_date - timedelta(days=1),
        time(hour=18, minute=0),
        tzinfo=draw_generated_at.tzinfo or timezone.utc,
    )

    if draw_generated_at > deadline:
        raise ValueError(
            f"Draw generated at {draw_generated_at.isoformat()} "
            f"after publication deadline {deadline.isoformat()}"
        )


# ============================================================
# VALIDATION: DRAW POSITIONS
# ============================================================

def validate_unique_draw_positions(draw_players: List[Dict]) -> None:
    """
    Ensure each draw position is used exactly once.
    """
    positions: List[int] = [int(r["draw_position"]) for r in draw_players]

    if len(positions) != len(set(positions)):
        raise ValueError("Duplicate draw_position detected in DrawPlayers")


# ============================================================
# VALIDATION: BYE ASSIGNMENT
# ============================================================

def validate_bye_allocation(draw_players: List[Dict]) -> None:
    """
    Validate bye allocation consistency.

    Rules:
    - A player with has_bye=True must exist only once
    - Number of byes must match structural expectation
    """
    bye_players = [r for r in draw_players if r.get("has_bye")]

    seen: Set[int] = set()
    for r in bye_players:
        pid = int(r["player_id"])
        if pid in seen:
            raise ValueError(f"Player {pid} assigned more than one bye")
        seen.add(pid)


# ============================================================
# VALIDATION: WITHDRAWN PLAYER ABSENCE
# ============================================================

def validate_withdrawn_player_absent(
    draw_players: List[Dict],
    withdrawn_player_id: Optional[int],
) -> None:
    """
    Ensure a pre-draw withdrawn player is not present in DrawPlayers.
    """
    if withdrawn_player_id is None:
        return

    for r in draw_players:
        if int(r["player_id"]) == int(withdrawn_player_id):
            raise ValueError(
                f"Withdrawn player {withdrawn_player_id} "
                f"present in DrawPlayers"
            )


# ============================================================
# AGGREGATE VALIDATION ENTRY POINT
# ============================================================

def validate_draw_players(
    *,
    draw_players: List[Dict],
    tournament_start_date: date,
    draw_generated_at: datetime,
    withdrawn_player_id: Optional[int] = None,
) -> None:
    """
    Run all DrawPlayers validations.
    """
    validate_draw_publication_deadline(
        tournament_start_date=tournament_start_date,
        draw_generated_at=draw_generated_at,
    )

    validate_unique_draw_positions(draw_players)
    validate_bye_allocation(draw_players)
    validate_withdrawn_player_absent(draw_players, withdrawn_player_id)


# ============================================================
# CLI / MANUAL EXECUTION
# ============================================================

def main() -> None:
    """
    Manual validation entry point.

    This function exists for:
    - debugging
    - ad-hoc validation
    - pipeline execution
    """
    raise RuntimeError(
        "validate_draw_players.py is a library module. "
        "Call validate_draw_players(...) from the pipeline."
    )


if __name__ == "__main__":
    main()
